### ISSUE TITLE
not scrobbling?

### ISSUE THREAD

**Issue by huvanile** [shiitake/Plax.FM#1]
thanks so much for tackling this!  I got it installed and setup correctly, but it doesn't seem to be scrobbling.  The permission authorization process went through just fine, and Plex is running. But, last.fm isn't registering that I've played music. Does the last.fm windows scrobbler app need to be installed?  I tried that and it doesnt seem to help.  lemme know.

**Comment by huvanile** [comment]
Not an issue, but more of an idea. (I'm new to git so I'm not sure if this is where this kind of stuff goes.)  In the system tray icon, maybe make it be different colors depending on whether the agent is started or stopped.  Other programs like wampserver do this and it helps the user know the status of the program without having to click on the system tray icon.

**Comment by shiitake** [comment]
Thanks for the feedback huvanile!
Sorry about the issue.  Is the service started? 
You should be able to see this in your Windows services (open Task Manager and select the services tab). Also if the service is started then the option on the system tray should be grayed out. 

If it's started but doesn't appear to be scrobbling there might be another issue. Can you post the logs for the service?   They should be found here: C:\ProgramData\Plax.FM\Logs{ServerName}-Plax.FM.log

**Comment by huvanile** [comment]
Thanks for the timely response!  Service is running.  Here are the logs:

10:46:12 INFO [1] [Topshelf.Ninject] Integration Started in host. 
10:46:12 DEBUG [1] Ninject kernel instantiated with 1 modules. 
10:46:13 INFO [1] [Topshelf.Quartz.Ninject] Quartz configured to construct jobs with Ninject. 
10:46:13 INFO [1] Configuration Result:
[Success] Name Plax.FM
[Success] DisplayName Plax.FM Scrobbling Service
[Success] Description Plax.FM Scrobbling Service
[Success] ServiceName Plax.FM 
10:46:13 INFO [1] Topshelf v3.1.135.0, .NET Framework v4.0.30319.34209 
10:46:13 DEBUG [1] Attempting to install 'Plax.FM' 
10:46:13 INFO [1] Installing Plax.FM Scrobbling Service service 
10:47:27 INFO [1] [Topshelf.Ninject] Integration Started in host. 
10:47:27 DEBUG [1] Ninject kernel instantiated with 1 modules. 
10:47:27 INFO [1] [Topshelf.Quartz.Ninject] Quartz configured to construct jobs with Ninject. 
10:47:27 INFO [1] Configuration Result:
[Success] Name Plax.FM
[Success] DisplayName Plax.FM Scrobbling Service
[Success] Description Plax.FM Scrobbling Service
[Success] ServiceName Plax.FM 
10:47:27 INFO [1] Topshelf v3.1.135.0, .NET Framework v4.0.30319.34209 
10:47:27 DEBUG [1] Starting Plax.FM 
10:47:27 INFO [1] [Topshelf.Ninject] Integration Started in host. 
10:47:27 DEBUG [1] Ninject kernel instantiated with 1 modules. 
10:47:28 INFO [1] [Topshelf.Quartz.Ninject] Quartz configured to construct jobs with Ninject. 
10:47:28 INFO [1] Configuration Result:
[Success] Name Plax.FM
[Success] DisplayName Plax.FM Scrobbling Service
[Success] Description Plax.FM Scrobbling Service
[Success] ServiceName Plax.FM 
10:47:28 INFO [1] Topshelf v3.1.135.0, .NET Framework v4.0.30319.34209 
10:47:28 DEBUG [1] Started by the Windows services process 
10:47:28 DEBUG [1] Running as a service, creating service host. 
10:47:28 INFO [1] Starting as a Windows service 
10:47:28 DEBUG [1] [Topshelf] Starting up as a windows service application 
10:47:28 INFO [6] [Topshelf] Starting 
10:47:28 DEBUG [6] [Topshelf] Current Directory: C:\Program Files (x86)\Shiitake Studios\Plax.Fm 
10:47:28 DEBUG [6] [Topshelf] Arguments:  
10:47:28 DEBUG [6] [Topshelf.Quartz] Scheduler starting up... 
10:47:28 INFO [6] [Topshelf.Quartz] Scheduled Job: DEFAULT.4861ee47-de2a-4ec5-a7cc-2828ea76aca3 
10:47:28 INFO [6] [Topshelf.Quartz] Job Schedule: Trigger 'DEFAULT.9704ee64-fb9a-4ee5-95ed-7da98c71c27b':  triggerClass: 'Quartz.Impl.Triggers.SimpleTriggerImpl calendar: '' misfireInstruction: 0 nextFireTime: 06/17/2015 15:47:28 +00:00 - Next Fire Time (local): 6/17/2015 10:47:28 AM -05:00 
10:47:28 INFO [6] [Topshelf.Quartz] Scheduler started... 
10:47:28 INFO [6] [Topshelf] Started 
10:47:28 INFO [10] Checking user configuration 
10:47:28 INFO [10] Job starting. 
10:47:28 INFO [10] Making working copy of Plex log. 
10:47:28 ERROR [10] There was an exception while attempting to make the copy of the Plex Media server log: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\germ\AppData\local\Plex Media Server\Logs\Plex Media Server.log'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at PlaxFm.Models.LogReader.CopyLog(String log) 
10:47:28 ERROR [10] Error attempting to start the job The process cannot access the file 'C:\ProgramData\Plax.FM\Logs\logcache.log' because it is being used by another process. System.IO.IOException    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at FileHelpers.FileHelperEngine.ReadFile(String fileName, Int32 maxRecords)
   at FileHelpers.FileDiffEngine.OnlyNewRecords(String sourceFile, String newFile)
   at PlaxFm.Models.LogReader.ReadLog(String plexLog, String logCache)
   at PlaxFm.Jobs.PlexJob.Start()
   at PlaxFm.Jobs.PlexJob.Execute(IJobExecutionContext context)
10:47:28 INFO [10] Job scheduled to run again at 06-17-2015 10:57 
10:56:01 INFO [1] [Topshelf.Ninject] Integration Started in host. 
10:56:01 DEBUG [1] Ninject kernel instantiated with 1 modules. 
10:56:01 INFO [1] [Topshelf.Quartz.Ninject] Quartz configured to construct jobs with Ninject. 
10:56:01 INFO [1] Configuration Result:
[Success] Name Plax.FM
[Success] DisplayName Plax.FM Scrobbling Service
[Success] Description Plax.FM Scrobbling Service
[Success] ServiceName Plax.FM 
10:56:01 INFO [1] Topshelf v3.1.135.0, .NET Framework v4.0.30319.34209 
10:56:01 DEBUG [1] Stopping Plax.FM 
10:56:01 INFO [5] [Topshelf] Stopping 
10:56:01 DEBUG [5] [Topshelf.Quartz] Scheduler shutting down... 
10:56:01 INFO [5] [Topshelf.Quartz] Scheduler shut down... 
10:56:01 INFO [5] [Topshelf] Stopped 
10:56:02 INFO [1] [Topshelf.Ninject] Integration Started in host. 
10:56:02 DEBUG [1] Ninject kernel instantiated with 1 modules. 
10:56:02 INFO [1] [Topshelf.Quartz.Ninject] Quartz configured to construct jobs with Ninject. 
10:56:02 INFO [1] Configuration Result:
[Success] Name Plax.FM
[Success] DisplayName Plax.FM Scrobbling Service
[Success] Description Plax.FM Scrobbling Service
[Success] ServiceName Plax.FM 
10:56:02 INFO [1] Topshelf v3.1.135.0, .NET Framework v4.0.30319.34209 
10:56:02 DEBUG [1] Uninstalling Plax.FM 
10:56:02 INFO [1] Uninstalling Plax.FM service 
11:01:55 INFO [1] [Topshelf.Ninject] Integration Started in host. 
11:01:55 DEBUG [1] Ninject kernel instantiated with 1 modules. 
11:01:55 INFO [1] [Topshelf.Quartz.Ninject] Quartz configured to construct jobs with Ninject. 
11:01:55 INFO [1] Configuration Result:
[Success] Name Plax.FM
[Success] DisplayName Plax.FM Scrobbling Service
[Success] Description Plax.FM Scrobbling Service
[Success] ServiceName Plax.FM 
11:01:55 INFO [1] Topshelf v3.1.135.0, .NET Framework v4.0.30319.34209 
11:01:55 DEBUG [1] Attempting to install 'Plax.FM' 
11:01:56 INFO [1] Installing Plax.FM Scrobbling Service service 
11:01:56 DEBUG [1] Opening Registry 
11:01:56 DEBUG [1] Service path: "C:\Program Files (x86)\Shiitake Studios\Plax.Fm\Plax.FM.exe" 
11:01:56 DEBUG [1] Image path: "C:\Program Files (x86)\Shiitake Studios\Plax.Fm\Plax.FM.exe"  -displayname "Plax.FM Scrobbling Service" -servicename "Plax.FM" 
11:01:56 DEBUG [1] Closing Registry 
11:02:03 INFO [1] [Topshelf.Ninject] Integration Started in host. 
11:02:03 DEBUG [1] Ninject kernel instantiated with 1 modules. 
11:02:03 INFO [1] [Topshelf.Quartz.Ninject] Quartz configured to construct jobs with Ninject. 
11:02:04 INFO [1] Configuration Result:
[Success] Name Plax.FM
[Success] DisplayName Plax.FM Scrobbling Service
[Success] Description Plax.FM Scrobbling Service
[Success] ServiceName Plax.FM 
11:02:04 INFO [1] Topshelf v3.1.135.0, .NET Framework v4.0.30319.34209 
11:02:04 DEBUG [1] Starting Plax.FM 
11:02:04 INFO [1] [Topshelf.Ninject] Integration Started in host. 
11:02:04 DEBUG [1] Ninject kernel instantiated with 1 modules. 
11:02:04 INFO [1] [Topshelf.Quartz.Ninject] Quartz configured to construct jobs with Ninject. 
11:02:04 INFO [1] Configuration Result:
[Success] Name Plax.FM
[Success] DisplayName Plax.FM Scrobbling Service
[Success] Description Plax.FM Scrobbling Service
[Success] ServiceName Plax.FM 
11:02:04 INFO [1] Topshelf v3.1.135.0, .NET Framework v4.0.30319.34209 
11:02:04 DEBUG [1] Started by the Windows services process 
11:02:04 DEBUG [1] Running as a service, creating service host. 
11:02:04 INFO [1] Starting as a Windows service 
11:02:04 DEBUG [1] [Topshelf] Starting up as a windows service application 
11:02:04 INFO [7] [Topshelf] Starting 
11:02:04 DEBUG [7] [Topshelf] Current Directory: C:\Program Files (x86)\Shiitake Studios\Plax.Fm 
11:02:04 DEBUG [7] [Topshelf] Arguments:  
11:02:04 DEBUG [7] [Topshelf.Quartz] Scheduler starting up... 
11:02:05 INFO [7] [Topshelf.Quartz] Scheduled Job: DEFAULT.9b2371e2-9fb1-461f-8f71-488a2899c244 
11:02:05 INFO [7] [Topshelf.Quartz] Job Schedule: Trigger 'DEFAULT.2992ef39-5c60-4385-915a-930e5498cf89':  triggerClass: 'Quartz.Impl.Triggers.SimpleTriggerImpl calendar: '' misfireInstruction: 0 nextFireTime: 06/17/2015 16:02:04 +00:00 - Next Fire Time (local): 6/17/2015 11:02:04 AM -05:00 
11:02:05 INFO [7] [Topshelf.Quartz] Scheduler started... 
11:02:05 INFO [7] [Topshelf] Started 
11:02:05 INFO [10] Checking user configuration 
11:02:05 INFO [10] Job starting. 
11:02:05 INFO [10] Making working copy of Plex log. 
11:02:05 ERROR [10] There was an exception while attempting to make the copy of the Plex Media server log: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\germ\AppData\local\Plex Media Server\Logs\Plex Media Server.log'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at PlaxFm.Models.LogReader.CopyLog(String log) 
11:02:05 INFO [10] Caching working copy of log 
11:02:05 INFO [10] Parsing logs for song entries. 
11:02:05 INFO [10] No new songs found. 
11:02:05 INFO [10] Job finished. 
11:02:05 INFO [10] Job scheduled to run again at 06-17-2015 11:12 
11:12:04 INFO [11] Checking user configuration 
11:12:04 INFO [11] Job starting. 
11:12:04 INFO [11] Making working copy of Plex log. 
11:12:04 ERROR [11] There was an exception while attempting to make the copy of the Plex Media server log: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\germ\AppData\local\Plex Media Server\Logs\Plex Media Server.log'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at PlaxFm.Models.LogReader.CopyLog(String log) 
11:12:04 INFO [11] Caching working copy of log 
11:12:04 INFO [11] Parsing logs for song entries. 
11:12:04 INFO [11] No new songs found. 
11:12:04 INFO [11] Job finished. 
11:12:04 INFO [11] Job scheduled to run again at 06-17-2015 11:22 
11:22:05 INFO [12] Checking user configuration 
11:22:05 INFO [12] Job starting. 
11:22:05 INFO [12] Making working copy of Plex log. 
11:22:05 ERROR [12] There was an exception while attempting to make the copy of the Plex Media server log: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\germ\AppData\local\Plex Media Server\Logs\Plex Media Server.log'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at PlaxFm.Models.LogReader.CopyLog(String log) 
11:22:05 INFO [12] Caching working copy of log 
11:22:05 INFO [12] Parsing logs for song entries. 
11:22:05 INFO [12] No new songs found. 
11:22:05 INFO [12] Job finished. 
11:22:05 INFO [12] Job scheduled to run again at 06-17-2015 11:32 
11:32:05 INFO [13] Checking user configuration 
11:32:05 INFO [13] Job starting. 
11:32:05 INFO [13] Making working copy of Plex log. 
11:32:05 ERROR [13] There was an exception while attempting to make the copy of the Plex Media server log: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\germ\AppData\local\Plex Media Server\Logs\Plex Media Server.log'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at PlaxFm.Models.LogReader.CopyLog(String log) 
11:32:05 INFO [13] Caching working copy of log 
11:32:05 INFO [13] Parsing logs for song entries. 
11:32:05 INFO [13] No new songs found. 
11:32:05 INFO [13] Job finished. 
11:32:05 INFO [13] Job scheduled to run again at 06-17-2015 11:42

**Comment by shiitake** [comment]
The main issue i'm seeing is that it can't seem to find the Plex server log: 

```
11:32:05 ERROR [13] There was an exception while attempting to make the copy of the Plex Media server log: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\germ\AppData\local\Plex Media Server\Logs\Plex Media Server.log'.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
at PlaxFm.Models.LogReader.CopyLog(String log) 
```

Can you actually navigate to C:\Users\germ\AppData\local\Plex Media Server\Logs\ and see the log file? If not it might mean that plex was installed under a different user profile.

**Comment by huvanile** [comment]
Yep, spot on.  There's no folder called "logs" in my c: drive's plex appdata folder.  

My guess:  A while back my plex had a bug where it kept filling up my c: drive with logs, thumbnails, and the like.  So, I had to configure Plex to store it's local application data on a different drive with lots of free space.  There's an advanced setting for this in the Plex server settings under "general" > "The path where local application data is stored".  I changed the default using this setting, and I think it causes the logs to be written in specified folder.

Work-around idea: Maybe you could code plax.fm to look for logs in the folder specified in this Plex configuration option?  Alternatively, make a user option available so I can specify the local application data folder that Plex uses (if not default)?

**Comment by shiitake** [comment]
I'll have to look into either pulling that location from the Plex API and/or letting users config it manually. 

As a workaround for today you could try to make a symbolic link pointing to the location of the correct log folder.  You would do this via command line: 

mklink /j "C:\Users\germ\AppData\local\Plex Media Server\Logs\" "E:\actual_log_folder\"

Obviously you'd want to make sure that the second part of the command points to the right folder.

**Comment by huvanile** [comment]
the link seems to have worked based on this log output, but still not scrobbling. it looks like its not seeing any songs in plex logs... is there a certain log setting I need to have enabled on Plex?  I turned on verbose logging but that doesn't seem to have helped.  

[Success] Name Plax.FM
[Success] DisplayName Plax.FM Scrobbling Service
[Success] Description Plax.FM Scrobbling Service
[Success] ServiceName Plax.FM 
15:37:36 INFO [1] Topshelf v3.1.135.0, .NET Framework v4.0.30319.34209 
15:37:36 DEBUG [1] Started by the Windows services process 
15:37:36 DEBUG [1] Running as a service, creating service host. 
15:37:36 INFO [1] Starting as a Windows service 
15:37:36 DEBUG [1] [Topshelf] Starting up as a windows service application 
15:37:36 INFO [7] [Topshelf] Starting 
15:37:36 DEBUG [7] [Topshelf] Current Directory: C:\Program Files (x86)\Shiitake Studios\Plax.Fm 
15:37:36 DEBUG [7] [Topshelf] Arguments:  
15:37:36 DEBUG [7] [Topshelf.Quartz] Scheduler starting up... 
15:37:36 INFO [7] [Topshelf.Quartz] Scheduled Job: DEFAULT.db2ccc15-479a-4541-9027-7882848985e3 
15:37:36 INFO [7] [Topshelf.Quartz] Job Schedule: Trigger 'DEFAULT.c2830a63-b90a-4aa1-a82c-8a3544aa305d':  triggerClass: 'Quartz.Impl.Triggers.SimpleTriggerImpl calendar: '' misfireInstruction: 0 nextFireTime: 06/17/2015 20:37:36 +00:00 - Next Fire Time (local): 6/17/2015 3:37:36 PM -05:00 
15:37:36 INFO [7] [Topshelf.Quartz] Scheduler started... 
15:37:36 INFO [7] [Topshelf] Started 
15:37:36 INFO [10] Checking user configuration 
15:37:36 INFO [10] Job starting. 
15:37:36 INFO [10] Making working copy of Plex log. 
15:37:36 INFO [1] The Plax.FM service was started. 
15:37:46 WARN [10] File lock operation has timed out. 
15:37:46 INFO [10] Caching working copy of log 
15:37:47 INFO [10] Parsing logs for song entries. 
15:37:47 INFO [10] No new songs found. 
15:37:47 INFO [10] Job finished. 
15:37:47 INFO [10] Job scheduled to run again at 06-17-2015 15:47 
15:47:36 INFO [11] Checking user configuration 
15:47:36 INFO [11] Job starting. 
15:47:36 INFO [11] Making working copy of Plex log. 
15:47:46 WARN [11] File lock operation has timed out. 
15:47:46 INFO [11] Caching working copy of log 
15:47:46 INFO [11] Parsing logs for song entries. 
15:47:46 INFO [11] No new songs found. 
15:47:46 INFO [11] Job finished. 
15:47:46 INFO [11] Job scheduled to run again at 06-17-2015 15:57 
15:57:36 INFO [12] Checking user configuration 
15:57:36 INFO [12] Job starting. 
15:57:36 INFO [12] Making working copy of Plex log. 
15:57:46 WARN [12] File lock operation has timed out. 
15:57:46 INFO [12] Caching working copy of log 
15:57:46 INFO [12] Parsing logs for song entries. 
15:57:46 INFO [12] No new songs found. 
15:57:46 INFO [12] Job finished. 
15:57:46 INFO [12] Job scheduled to run again at 06-17-2015 16:07 

Thoughts?

**Comment by shiitake** [comment]
Good that the service is running - it looks like it may not have found any songs in the most recent log file. 

While the Plax.FM service is running - go ahead and listen to a few songs and then check back in the logs. Also make sure the songs are on your local server (i.e. not streaming from a friend's Plex server). 

If you're still not seeing that their scrobbling let me know - I'll probably want to get the most recent Plex Server Log from you (via dropbox or pastebin).

**Comment by huvanile** [comment]
i think it requires debug logging to be enabled... testing now

**Comment by huvanile** [comment]
WORKS!  The Plex server needs debug logging enabled.    There's an advanced server option called "Enable Plex Media Server debug logging" under "General".  Once I turned that on it started working.  Thanks for your help with this sir.

09:17:36 INFO [16] Making working copy of Plex log. 
09:17:46 WARN [16] File lock operation has timed out. 
09:17:53 INFO [16] Caching working copy of log 
09:17:53 INFO [16] Parsing logs for song entries. 
09:17:59 INFO [16] Retrieving song data from songlist. 
09:17:59 INFO [16] 2 new song(s) found. 
09:17:59 INFO [16] Scrobbling song entries. 
09:17:59 INFO [16] Job finished. 
09:17:59 INFO [16] Job scheduled to run again at 06-18-2015 09:27 
09:17:59 INFO [7] Scrobbled Barenaked Ladies - The Old Apartment 
09:17:59 INFO [7] Scrobbled Barenaked Ladies - Brian Wilson

**Comment by shiitake** [comment]
That's great news! I've updated our installation instructions so other folks will know that debug logging needs to be enabled. 

Thanks for your help in sorting this out!
