### ISSUE TITLE
system tray icon color to reflect status

### ISSUE THREAD

**Issue by huvanile** [shiitake/Plax.FM#2]
Not an issue, but more of an idea. (I'm new to git so I'm not sure if this is where this kind of stuff goes.) In the system tray icon, maybe make it be different colors depending on whether the agent is started or stopped. Other programs like wampserver do this and it helps the user know the status of the program without having to click on the system tray icon.

**Comment by shiitake** [comment]
I really like this idea! 

I'm going to flag this is a feature request and add it to the list for the next update.

**Comment by shiitake** [comment]
Closing this issue but I've added this to the trello board managing feature requests.
- [Color Change for Systray Icon Based on Service Status](https://trello.com/c/L57YtiBs)
