### ISSUE TITLE
[IDEA] Auto-start with Windows

### ISSUE THREAD

**Issue by huvanile** [shiitake/Plax.FM#3]
Not an issue, just an idea:  It would be cool to have the option for the program to auto-start with Windows and have the scrobbler auto-start as well. This would make it an "install it and forget" piece of software.

**Comment by shiitake** [comment]
Closing this issue but I've added this to the trello board tracking feature requests: 
- [Implement Auto-start with Service](https://trello.com/c/fz1cYplS)
